require('settings.render-markdown')
require('settings.smear_cursor')
require('settings.hlchunk')
require('settings.blink')
require('settings.noice')

require('tiny-inline-diagnostic').setup({})
require('dropbar').setup({})
require('colorizer').setup()
require('notify').setup({})
