require('settings.nvim-treesitter')
require('settings.smear_cursor')
require('settings.lsp-colors')
require('settings.nvim-cmp')
require('settings.lspkind')
require('settings.noice')
-- require('settings.dap')
-- require('settings.lspsaga')
require('colorizer').setup()
require('hlchunk').setup({})
require('dropbar').setup()
require('notify').setup()
-- require('dapui').setup()
